### ISSUE TITLE
Getting 500 - Internal server error.after insatlling ebor framework

### ISSUE THREAD

**Issue by googlerajjo** [tommusrhodus/Ebor-Framework#2]
Help me with issue
I am getting: 500 - Internal server error.after insatlling ebor framework plugin for Pivot WPTheme on godaddy.
But in my pc on wamp server its working fine
So please help me
Is there any other alternative to ebor framework for my pivot theme
And also i am getting same error in tools > importing > wordpress
I already tried by editing wp-config (adding:     define('WP_MEMORY_LIMIT', '64M');     )
but getting no solution

**Comment by billpatrianakos** [comment]
Trying to help my girlfriend set up the Finch theme which requires this plugin and I'm seeing the following PHP error whenever we trying to activate it:

`PHP Fatal error:  Cannot redeclare aqpb_get_version() (previously declared in /srv/www/pressit.me/public_html/wp-content/plugins/Ebor-Framework-master/page-builder/aqua-page-builder.php:17) in /srv/www/pressit.me/public_html/wp-content/plugins/aqua-page-builder/aqua-page-builder.php on line 42, referer: http://litterbearsphotography.com/wp-admin/plugins.php`

This is a site on a Multisite install. I'm thinking it may be related.

**Comment by tommusrhodus** [comment]
@billpatrianakos your error clearly points to the aqua page builder plugin you also have installed on your server, this is un-needed, please delete.
