### ISSUE TITLE
Update from 1.0.9 to 1.3.1 loses theme customization preview and staging environment missing Template section content

### ISSUE THREAD

**Issue by cptncrnch** [tommusrhodus/Ebor-Framework#21]
I'm updating the Ebor Framework plug-in on a staging site for a Wordpress (v4.6.6) site. The staging site has an identical copy of the production database (renamed with prefix "staging_*") and wp-content folders: plugins, themes, and uploads. The production site path is `http://www.domain.com/site` while the staging site path is `http://www.domain.com/staging/site`. The staging database was updated to reflect the site path changes
`UPDATE wp_options SET option_value = REPLACE(option_value, 'http://www.domain.com/site', 'http://www.domain.com/staging/site');
UPDATE wp_postmeta SET meta_value = REPLACE(meta_value, 'http://www.domain.com/site', 'http://www.domain.com/staging/site');
UPDATE wp_posts SET guid = REPLACE(guid, 'http://www.domain.com/site', 'http://www.domain.com/staging/site');
UPDATE wp_posts SET post_content = REPLACE(post_content, 'http://www.domain.com/site', 'http://www.domain.com/staging/site');`

Otherwise, the staging site has the standard Wordpress files that come with a fresh installation.

The Permalinks settings (Settings > Permalinks) are resaved to "refresh" the site wide links.

Here is what the Ebor Framework v1.09 looks like in the production site's wp-admin portal:
- The "Finch WP" theme is installed.
- Hovering over the Dashboard button shows an option for "Finch WP Theme Options" underneath "Home" and "Updates".
- Hovering over the Appearance button shows an option for "Ebor Page Builder" between "Background" and "Editor".
- Clicking on "Finch WP Theme Options" from the Dashboard button OR clicking "Customize" from the Appearance button navigates to the theme customization.
- In theme customization, the right preview pane shows the staging site's home page.
- In theme customization, underneath the Active Theme, the order of the settings available are: Finch WP: Demo Data, Site Identify, Background Image, Menus, Widgets, Static Front Page, Finch WP: Styling Settings, Finch WP: Header Settings, Finch WP: Blog Settings, Finch WP: Portfolio Settings, Finch WP: Footer Settings.
- In Edit Page, the "Add Template" and "Template Builder" buttons are present.

After setting up the staging environment, in the staging wp-admin portal, Appearance > Ebor Page Builder, **saved Templates are missing Section Content**.

When I update the Ebor Framework plug-in on the staging site from 1.0.9 to 1.3.1 from the Update Plugins page, these are the update details:
> Downloading update from http://wp-updates.com/api/1/download/plugin/84vj8pGDQRCA853TIx57Eg/index…
> Unpacking the update…
> Installing the latest version…
> Removing the old version of the plugin…
> Plugin updated successfully.

Then I navigate to the Plugins page (or any page for the wp-admin portal to refresh). Here is what Ebor Framework v1.3.1 looks like on the staging site's wp-admin portal:
- The "Finch WP" theme is installed.
- Hovering over the Dashboard button **does not show** an option for "Finch WP Theme Options" underneath "Home" and "Updates".
- Hovering over the Appearance button shows an option for "Ebor Page Builder" between "Background" and "Editor".
- In Edit Page, the "Add Template" and "Template Builder" buttons are present.
- Clicking on "Customize" from the Appearance button navigates to the theme customization.
- In theme customization, **the right preview pane is blank**.
- In theme customization, underneath the Active Theme, the order of the settings available are: Ebor Framework: Update Settings (**new setting**), Finch WP: Demo Data, Site Identify, Background Image, Menus, Widgets, Static Front Page, Finch WP: Styling Settings, Finch WP: Header Settings, Finch WP: Blog Settings, Finch WP: Portfolio Settings, Finch WP: Footer Settings.

I followed instructions to enter in an Envato username and API key in "Ebor Framework: Update Settings". However, it doesn't fix the issue.

As of now, the staging site loads fine still. I'm able to create New Posts with templates from Ebor Page Builder. Is there something else I can try to test if the staging environment setup or plug-in update was successful?

**Comment by cptncrnch** [comment]
Just noticed also that in the Ebor Page Builder, the Section Content for saved Templates were lost in the update. For example, the production site has a Template with Section Content that included Tabs & Accordian content, however in the staging site the same saved Template is missing the Tabs & Accordian content.

**Comment by tommusrhodus** [comment]
Hey there,

1. Finch needs an update to handle an update I made to Ebor Framework recently. Basically for now, if you're changing or previewing themes, make sure you do it in "appearance => themes" only, not in the customiser. To get the functionality back, in "appearance => themes" switch to a default theme, and then switch back to re-initialise all the missing items.

2. You're missing data because you did not move your database via a serialisation handler. A simple find/replace on a database is not the correct way to handle data as it breaks data serialisation, use a plugin designed to handle this: https://wordpress.org/plugins/wp-migrate-db/

3. Please use our tickets for theme & plugin support: https://tommusrhodus.ticksy.com

Cheers - Tom
