### ISSUE TITLE
HTTP ERROR 500 After installing

### ISSUE THREAD

**Issue by nahuelcandia** [tommusrhodus/Ebor-Framework#22]
The wordpress website crashes after installing the plugin. 
Error: 
HTTP ERROR 500
Fatal error: Call to undefined function cmb2_bootstrap() in htdocs/wp-content/plugins/Ebor-Framework-master/metaboxes/init.php on line 105

When is removed, the website works again.
Theme: Pillar

**Comment by tommusrhodus** [comment]
For all theme support, please use our tickets: https://tommusrhodus.ticksy.com
