### ISSUE TITLE
ebor_video_inline_shortcode uses wp_oembed_get which is not cached, leading to excessive external requests

### ISSUE THREAD

**Issue by khromov** [tommusrhodus/Ebor-Framework#26]
As topic states, `wp_oembed_get()` calls are not cached, so every time you display a page containing a "Video inline embed" it shoots off a server-side request to the host of the video, ie YouTube, making the pageload very slow.

**Comment by khromov** [comment]
I believe the oEmbed block provides a much better user experience than users pasting iframes. Just wrap your `wp_oembed_get()` call in a small transient-based cache layer.

```
...
$oembed_url = 'https://www.youtube.com/watch?v=oits7sq4nX0';
$cache_key = 'tr-oembed-' . md5($oembed_url);

//Bail early on result
 if($result = get_transient($cache_key)) {
    return $result;
}

//Cache is empty, resolve oEmbed
$oembed_result = wp_oembed_get($url, $args);

//Cache 4 hours for standard and 5 min for failed
$ttl = $oembed_result ? 14400 : 300;

update_transient($cache_key, $oembed_result, $ttl);

return $oembed_result;
...
```

**Comment by tommusrhodus** [comment]
Can't say fairer than that, thanks for the input, investigating and testing.
