### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by voidzone** [tommusrhodus/Ebor-Framework#27]
/wordpress-importer/wordpress-importer.php
line 756

Change from
`$$meta['key'] = $meta['value'];`
To
`${$meta['key']} = $meta['value'];`

http://us1.php.net/manual/en/migration70.incompatible.php

**Comment by tommusrhodus** [comment]
Thanks for letting us know, investigating this now.

Cheers - Tom
