### ISSUE TITLE
Adding hooks to register post type

### ISSUE THREAD

**Issue by tomrainedotcom** [tommusrhodus/Ebor-Framework#28]
More of a request than anything. Could you add filters to the custom post type register functions similar to 

`register_post_type( 'portfolio', apply_filters( 'ebor_cpt_init', $args, "portfolio") );
register_post_type( 'team', apply_filters( 'ebor_cpt_init', $args, "team") );
register_post_type( 'client', apply_filters( 'ebor_cpt_init', $args, "client") );`

**Comment by tommusrhodus** [comment]
Looks good, checking this one over now

**Comment by tomrainedotcom** [comment]
Thanks for adding this in.
