### ISSUE TITLE
Pleas update bundled version of CMB2 

### ISSUE THREAD

**Issue by jtsternberg** [tommusrhodus/Ebor-Framework#3]
Older version broke the no-conflict mode feature. If you update to the most recent, it should be fixed. 
See: https://wordpress.org/support/topic/doesnt-work-with-ebor-framework?replies=2#post-8402968

**Comment by tommusrhodus** [comment]
Hey, thanks for the heads up mate!

**Comment by jtsternberg** [comment]
👍
