### ISSUE TITLE
foundry_vc_shortcodes is 0 causing shortcodes not to process

### ISSUE THREAD

**Issue by jas8522** [tommusrhodus/Ebor-Framework#32]
After a Foundry theme update and WordPress update foundry_vc_shortcodes is 0, meaning shortcodes like [foundry_slider_content image=”4795″] stop working and instead display on the page.

I'm not entirely sure how to fix this properly, so my workaround has been to simply edit the defaults array in init.php and manually set: 'foundry_vc_shortcodes'    => '1'

Which solves the problem... at least until the framework updates next.

My guess is that ebor_framework_clean_theme_options set to to 0, but the Foundry theme itself is supposed to be setting it to 1 in order to delcare its needs... but that's not happening.

I also thought perhaps Foundry should be allowing me to enable this within Customizer under Ebor Framework: Update Settings, but the only option within that settings pane  is "User Settings" and the Envato username and API key.

How do I ensure this is fixed permanently?

**Comment by tommusrhodus** [comment]
Hey there,

This is just a one off, the simplest way is to switch to a new theme in "appearance => themes" and then directly back to Foundry in the same window, "Appearance => themes", this will trigger everything needed.

This is a one time issue as we had to make a number of changes to Foundry to keep it inline with the current standards on Themeforest.

Cheers - Tom
