### ISSUE TITLE
All admin menu and setting are gone

### ISSUE THREAD

**Issue by Manzurul** [tommusrhodus/Ebor-Framework#33]
Hello,

I m using Ebor Framework Version 1.4.4. for some reason i have turn of the plugin and turn on it but after turn on i dont see any admin menu any more for ex portfolio, team and client all area gone even if i tried to open by url /wp-admin/edit.php?post_type=portfolio i got this error "Invalid post type."!!

**Comment by tommusrhodus** [comment]
For all theme support please use a ticket, we do not provide theme support via GitHub

https://tommusrhodus.ticksy.com

**Comment by Manzurul** [comment]
Never mind i have solved that already. Thanks for your reply
