### ISSUE TITLE
Bug on First install in localhost

### ISSUE THREAD

**Issue by MaloRchrd** [tommusrhodus/Ebor-Framework#42]
It is the third time I try to install pillar theme locally as a child theme and every time I get this error during the plugin installation  of Plugin Ebor Framework

```
Starting package doawnloading from https://github.com/tommusrhodus/ebor-framework/archive/master.zip…
An error occurred while installing Ebor Framework: <strong>The download failed. cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version</strong>.
```

And when i get back to the main screen TGMA keep pushing me the installation of the plugin 
and every time I try I get the same error as above plus this: 

`Plugin not activated. A higher version of Ebor Framework is needed for this theme. Please update the plugin.`

**Comment by tommusrhodus** [comment]
As the issue mentions, your local server is having cURL issues, and you should just install this manually by downloading the main archive .zip of this repo and adding to "plugins => add new"
