### ISSUE TITLE
Portfolio's additional items arrangement

### ISSUE THREAD

**Issue by nivago** [tommusrhodus/Ebor-Framework#43]
On Portfolio editing page, at post layout options, additional items can be added. While they appear on published page in exact same order they were added, sometimes you need to re-arrange them. There are two button-styled "a" links with CSS classes "button-secondary cmb-shift-rows move-up alignleft" and "button-secondary cmb-shift-rows move-down alignleft", yet they don't seem to work, additional items do not change their order.

No errors in developers console, tested with WP 4.9.8, Ebor Framework 1.4.11 on Mozilla Firefox 62.0.2 and Google Chrome 69.0.3497.100.

**Comment by tommusrhodus** [comment]
Hey there @nivago -- first of all, sorry for the slow reply here. I've tested this using our current theme framework version and we're having no problem with this functionality. Likewise, this is the only report of this, so I'm certain this would relate to your own setup in some way.

If you'd like us to look at this further with you, you'll need to use a ticket, as in testing, this functionality is working fine.

https://tommusrhodus.ticksy.com

Cheers - Tom
