### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function ebor_before_block()

### ISSUE THREAD

**Issue by justiny** [tommusrhodus/Ebor-Framework#51]
Hi,

Getting this error when attempting to access any page with the page builder:

```
Fatal error: Uncaught Error: Call to undefined function ebor_before_block() in /www/wp-content/plugins/ebor-page-builder-master/classes/class-aq-block.php:164
```

Thanks for any help!

**Comment by tommusrhodus** [comment]
Hey Justiny,

Are you using one of my themes, or is this issue with a custom theme? If this is a custom theme, you'll need to define those functions in the theme itself. If you're using one of our themes, drop us a support ticket: https://tommusrhodus.ticksy.com

Cheers - Tom
