### ISSUE TITLE
Featured Image column in Woocommerce product pages is compacted with no width applied

### ISSUE THREAD

**Issue by sara5387** [tommusrhodus/Ebor-Framework#53]
The featured image column on the regular posts page in Wordpress looks fine, however, on the Woocommerce products page the column is compacted and each letter of the text "featured image" is on a new line which causes the table header to be way too tall and takes up a lot of space. A width has not been applied to the column, which works fine as I said, on the regular Wordpress posts page, but on the Woocommerce products page, it would have to have a width applied as all the other columns has it.

![column-width-issue](https://user-images.githubusercontent.com/51741998/67156206-e7322300-f31b-11e9-8af9-4699585252a0.png)

**Comment by tommusrhodus** [comment]
Please see commit e3fdb7f -- or use the [screen-options] tab in the top right of that screen to turn off the featured image column.

Cheers - Tom
