### ISSUE TITLE
Ebor Framework causes title in admin Posts to be collapsed.

### ISSUE THREAD

**Issue by sara5387** [tommusrhodus/Ebor-Framework#54]
The title column is much narrower than it should be in the admin posts page. I'm guessing it's because of the added thumbnail column. Below is images of how it looks with ebor framework and without.

With ebor:

![ebor-framework-collapsed-title-column](https://user-images.githubusercontent.com/51741998/76518642-c3ed4900-645f-11ea-8238-ba7fa44242ac.png)

Without ebor:

![ebor-framework-collapsed-title-column-2](https://user-images.githubusercontent.com/51741998/76518924-4a098f80-6460-11ea-8c76-3c61e2519b9c.png)

Should probably be an easy fix.

**Comment by tommusrhodus** [comment]
Good afternoon Sara,

I can see a number of other columns in your view that are also adding to the overall available width, such as your "stats" column. If you don't want the featured image column, you can hide it using "screen options" in the top right of your admin.

Cheers - Tom

**Comment by sara5387** [comment]
Hello.
Right, I think that will have to be the best solution for now. Wordpress should really try to fix that somehow so that the title column always has a good width, even if plugin/theme creators adds extra columns to it.

Thanks.
