### ISSUE TITLE
Hi Tom!

### ISSUE THREAD

**Issue by Nirvsoner** [tommusrhodus/Ebor-Framework#7]
Hey @tommusrhodus, hope you doing well :) can I use your framework in a ThemeForest theme I'm creating? Thanks in advance.

**Comment by tommusrhodus** [comment]
Yes feel free, though please fork it! I release updates regularly to cover my themes specifically, if you use it without forking your users could run into issues as I release updates. Also, remove the wp-updates-theme call for the same reason :)
